production:
  auto_create: false
  deny_delete: false
  svn:
    path: /var/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
    chown:
      user: uid
      group: gid
    

staging:
  auto_create: false
  deny_delete: false
  svn:
    path: /var/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
    chown:
      user: uid
      group: gid

development:
