production:
  auto_create: false
  deny_delete: false
  svn:
    path: /var/svn
    svnadmin: /usr/bin/svnadmin
    url: svn

staging:
  auto_create: false
  deny_delete: false
  svn:
    path: /var/svn
    svnadmin: /usr/bin/svnadmin
    url: svn

development:
