production:
  auto_create: true
  deny_delete: true
  svn:
    path: /var/lib/svn
    svnadmin: /usr/bin/svnadmin
    url: svn
  git:
    path: /var/lib/git
    git: /usr/bin/git
    url: http://git.myhost.com

development:
